name: Lint checks
on: [push]
jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run selectorcheck
      - run: npm run typecheck
      - run: npm run lint
